name: RNAgrinder
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - star=2.7.11a
    - picard=2.27.4
    - bioawk=1.0
    - fastqc=0.12.1
    - fastp=0.23.4
    - samtools=1.18
    - csvtk=0.30.0
    - bioconductor-ngsreports=2.0.0
    - kraken2=2.1.3
    - bracken=2.9
    - mosdepth=0.3.3
    - multiqc=1.21
    - nextflow
    - r-ggplot2
    - r-gplots
    - r-gsalib
    - r-argparse
    - rna-seqc
    - ribodetector=0.3.1
    - python==3.9
    - bx-python
    - pip=24.0
    - r-biocmanager
    - bioconductor-biocstyle 
    - r-dygraphs
    - r-r.utils
    - gnuplot=5.0.3
    - sortmerna=4.3.6
    - seqkit=2.8.0
    - pip:
        - bx
